name: "Bug report"
description: "Reporta un error"
labels: ["bug"]
body:
  - type: textarea
    id: steps
    attributes: { label: "Pasos para reproducir", placeholder: "..." }
    validations: { required: true }
  - type: textarea
    id: expected
    attributes: { label: "Comportamiento esperado", placeholder: "..." }
  - type: textarea
    id: actual
    attributes: { label: "Comportamiento actual", placeholder: "..." }
