name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  linux-py312:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Preinstall
        run: |
          python -m pip install -U pip
          pip install -U ruff black mypy pytest build

      - name: Install editable
        run: pip install -e .

      - name: Run checks (log único)
        run: |
          : > ci.log
          echo '$ ruff check .' | tee -a ci.log
          ruff check . 2>&1 | tee -a ci.log
          echo '$ ruff format --check .' | tee -a ci.log
          ruff format --check . 2>&1 | tee -a ci.log
          echo '$ black --check .' | tee -a ci.log
          black --check . 2>&1 | tee -a ci.log
          echo '$ pytest -q' | tee -a ci.log
          pytest -q 2>&1 | tee -a ci.log
          echo '$ mypy .' | tee -a ci.log
          mypy . 2>&1 | tee -a ci.log
          echo '$ python -m build' | tee -a ci.log
          python -m build 2>&1 | tee -a ci.log

      - name: Smoke import wheel
        run: |
          python - <<'PY'
          import glob, subprocess, sys
          ws = glob.glob("dist/*.whl"); assert ws, "wheel not built"
          subprocess.check_call([sys.executable,"-m","pip","install",ws[0]])
          import header_guardian as m; print("import OK", getattr(m,"__version__","?"))
          PY

      - name: Upload job log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ci-log-py312
          path: ci.log
          if-no-files-found: warn
          retention-days: 7
