name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux-py311:
    name: python-3.11 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -U pip
      - run: pip install -U ruff black mypy pytest build
      - run: pip install -e .
      - run: ruff check .
      - run: ruff format --check .
      - run: black --check .
      - run: pytest -q
      - run: mypy .
      - name: Build wheel
        run: python -m build
      - name: Install built wheel & smoke
        run: |
          python - <<'PY'
          import glob, subprocess, sys
          ws = glob.glob("dist/*.whl"); assert ws, "wheel not built"
          subprocess.check_call([sys.executable,"-m","pip","install","-U","pip"])
          subprocess.check_call([sys.executable,"-m","pip","install",ws[0]])
          import header_guardian as m; print("import OK", getattr(m,"__version__","?"))
          PY

  linux-py312:
    name: python-3.12 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: python -m pip install -U pip
      - run: pip install -U ruff black mypy pytest build
      - run: pip install -e .
      - run: ruff check .
      - run: ruff format --check .
      - run: black --check .
      - run: pytest -q
      - run: mypy .
      - name: Build wheel
        run: python -m build
      - name: Install built wheel & smoke
        run: |
          python - <<'PY'
          import glob, subprocess, sys
          ws = glob.glob("dist/*.whl"); assert ws, "wheel not built"
          subprocess.check_call([sys.executable,"-m","pip","install","-U","pip"])
          subprocess.check_call([sys.executable,"-m","pip","install",ws[0]])
          import header_guardian as m; print("import OK", getattr(m,"__version__","?"))
          PY
