name: CI
on:
  push: { branches: [ main ] }
  pull_request:
  workflow_dispatch:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
permissions: { contents: read }

jobs:
  linux:
    name: python-${{ matrix.py }} on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: { py: ["3.11","3.12"] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.py }} }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.py }}-${{ hashFiles('pyproject.toml') }}
      - run: python -m pip install -U pip build
      - run: python -m build
      - run: python -m pip install dist/*.whl
      - run: python -m pip install ruff==0.6.9 black==24.10.0 pytest==8.4.2 mypy==1.17.1
      - run: ruff check .
      - run: black --check .
      - run: ruff format --check .
      - run: pytest -q
      - run: mypy .

  windows:
    name: python-${{ matrix.py }} on windows-latest
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix: { py: ["3.11","3.12"] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.py }} }
      - run: python -m pip install -U pip build
      - run: python -m build
      - run: python -m pip install dist/*.whl
      - run: python -m pip install ruff==0.6.9 black==24.10.0 pytest==8.4.2 mypy==1.17.1
      - run: ruff check .
      - run: black --check .
      - run: ruff format --check .
      - run: pytest -q
      - run: mypy .
